### ISSUE TITLE
loadmore为何不做成跟ptr的方式一样？

### ISSUE THREAD

**Issue by xu6148152** [etao-open-source/cube-sdk#66]
现在的方式是作为view的一部分，感觉这样耦合在一起了。特别是对于recyclerview，要使用loadmore的话，几乎所有的原来的viewholder全都要改。。。

**Comment by KANGOD** [comment]
同意。虽然可以实现，但是用 View 的 item 来显示 load more hint，耦合太太太严重了，而且不同的 View 要用不同的方法来实现同一个功能(load more)，太琐碎。像 ptr 一样，附加一个 footerView 作为 load more hint view，封装 load more 这一功能，使之对于 ptr 支持的 View 类型全部支持，才是更好的设计吧？
